import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Navbar Start Here */}
        <header id="header">
          <a href="#" id="logo">
            Fatima
          </a>

          <nav id="nav">
            <a href="/">Home</a>
            <a href="./Aboutme">About Me</a>
            <a href="./Contact">Contact</a>
          </nav>
        </header>

        {/* Navbar Ends Here */}

        {children}
      </body>
    </html>
  );
}


